Traceback (most recent call last):
  File "sample_fit.py", line 34, in <module>
    num_boot = 200, cores = cpu_count())
  File "/storage/work/s/szk381/mrexo/mrexo/fit.py", line 175, in fit_mr_relation
    degree_max=degree_max, k_fold=k_fold, cores=cores, save_path=aux_output_location, abs_tol=abs_tol)
  File "/storage/work/s/szk381/mrexo/mrexo/cross_validate.py", line 64, in run_cross_validation
    cv_result = list(pool.imap(cv_parallelize,cv_input))
  File "/storage/home/szk381/.conda/envs/pyvenv/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
ValueError: shapes (25,) and (9,4) not aligned: 25 (dim 0) != 9 (dim 0)
